<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f26f1966-4b59-4215-88b0-01b71ce7b871</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Configuraciones\" />
    <Folder Include="Datos\" />
    <Folder Include="Entidades\" />
    <Folder Include="Jobs\" />
    <Folder Include="Servicios\" />
    <Folder Include="Utilidades\" />
    <Folder Include="Views\Comentarios\" />
    <Folder Include="Views\Entradas\" />
    <Folder Include="Views\Home\Componentes\" />
    <Folder Include="wwwroot\img\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Usuarios\RolesUsuario.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OpenAI" Version="2.1.0" />
  </ItemGroup>

</Project>
